sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install .[test]
  # Install through setup.py should be redundant because of the preceding pip
  # install. Just doing this to try to catch any high-level errors.
  - python setup.py install

# command to run tests
script:
  - python setup.py ci
